name: deploy

on: push

jobs:
  deploy:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run deploy
        run: |
          echo "Deploying..."
        env:
          DEFAULT-BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
